// <auto-generated />
using System;
using AdminApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminApi.Models.AboutContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HeadlineAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadlineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParagraphsAr")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ParagraphsEn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AboutContents");
                });

            modelBuilder.Entity("AdminApi.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("AdminApi.Models.AlsoBuiltItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("AlsoBuiltItems");
                });

            modelBuilder.Entity("AdminApi.Models.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("AdminApi.Models.EducationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DegreeAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DegreeEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeriodAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeriodEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("EducationEntries");
                });

            modelBuilder.Entity("AdminApi.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chips")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("ParagraphAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParagraphEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeriodAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeriodEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("AdminApi.Models.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("AdminApi.Models.SiteConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailabilityLineAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvailabilityLineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactIntroAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactIntroEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactMetaAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactMetaEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactBarAr")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FactBarEn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FooterCopyrightAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterCopyrightEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroHeadlineLinesAr")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HeroHeadlineLinesEn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("HeroSublineAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroSublineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitialsAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitialsEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text");

                    b.Property<string>("SocialLinks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TaglineAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaglineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SiteConfigs");
                });

            modelBuilder.Entity("AdminApi.Models.StackGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("StackGroups");
                });

            modelBuilder.Entity("AdminApi.Models.WorkCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadlineAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadlineEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumberEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanelDataJsonAr")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PanelDataJsonEn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PanelKind")
                        .HasColumnType("integer");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StackLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("WorkCases");
                });
#pragma warning restore 612, 618
        }
    }
}
